#
# This is free software, lisence use MIT.
#
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
#
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: OpenWrt-CI

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Env setup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential
          ls -al
      - name: Update
        run: |
          make init
      - name: Compile
        run: |
          make amd64 OPT=-DNOLIMIT
          ls -al

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: artifact
          path: ./tinyvpn_amd64
